trigger:
- main

- task: AzureFunctionApp@2
  inputs:
    appType: 'functionAppLinux'
    appName: 'DeployAzureDevOps'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    deploymentMethod: 'auto'