trigger:
- main

- task: AzureFunctionApp@2
  inputs:
    connectedServiceNameARM: 'Pay-As-You-Go(efe6f822-b14e-443e-a09e-75d116511fad)'
    appType: 'functionAppLinux'
    appName: 'DeployAzureDevOps'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    deploymentMethod: 'auto'